name: Promote to production

on:
  workflow_dispatch:

concurrency:
  group: ibmi-mcp-server-production
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
