name: Deploy to development

on:
  push:
    branches: [feat/entra-oauth-support]
  workflow_dispatch:

concurrency:
  group: ibmi-mcp-server-development
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
